
= CHECKCHLD(2)
:doctype: manpage

== NAME
CHECKCHLD - check the status of a child after SIG_CHLD, and release the child's resources

== SYNOPSIS
Input::
	* C=0 - search for newly suspended child tasks
	* C=1 - search for newly killed child tasks
Call::
	jsr CHECKCHLD
Output::
	* C=0 - found a child
		** AC - child return code (for killed children; invalid for suspended)
		** XR - task ID of dead/suspended child
	* C=1 - no child found

NOTE: YR is preserved

== DESCRIPTION
Checks the list of child tasks of the caller, whether one has died resp. has been suspended, and returns the task ID. In case a dead child was found, it returns the return code of the child task.

NOTE: the information for dead children is only available when the child died while in the parent SIG_CHLD was set.


== SEE ALSO
link:../signals.7.adoc[signals(7)],
link:SENDSIG.2.adoc[SENDSIG(2)],
link:SETSIG.2.adoc[SETSIG(2)]

== AUTHOR
Written by André Fachat.

== REPORTING BUGS
Please report bugs at https://github.com/fachat/GeckOS-V2/issues

