
= SENDSIG(2)
:doctype: manpage

== NAME
SENDCTRL - send a signal to the foreground task attached to a stream

== SYNOPSIS
Input::
	** AC - signal mask to send
	** XR - stream
Call::
	jsr SENDCTRL
Output::
	* C=1 - error
		** AC - error code
	* C=0 - success


== DESCRIPTION
Sends a signal to another task. The task is determined by the foreground task attached to the given stream.
In the target process the bit corresponding to the signal is set in the
pending signal bitmap of the receiving task.

Note, that this function is mainly called from within the streams code.

== RETURN CODES
Error return codes are given when at return, C=1.

E_OK::
	signal was delivered successfully
E_NOTASK::
	the stream did not have an attached foreground task
E_NOSTR::
	Not a valid stream number

== SEE ALSO
link:../signals.7.adoc[signals(7)],
link:SENDSIG.2.adoc[SENDSIG(2)],
link:SETLMODE.2.adoc[SETLMODE(2)]

== AUTHOR
Written by André Fachat.

== REPORTING BUGS
Please report bugs at https://github.com/fachat/GeckOS-V2/issues

