
= STRCMD(2)
:doctype: manpage

== NAME
STRCMD - various stream commands

== SYNOPSIS
Input::
	* AC - command to execute on stream
	* XR - stream number (except for SC_GET)
	* YR - 
		** bits to set/clear in SC_SSTAT/SC_CSTAT
		** foreground PID in SC_FGPID
		** signal mask in SC_FGSIG

Call::
	jsr STRCMD
Output::
	* C=0
		** AC - value depending on command
		** YR - value depending on command
	* C=1
		** AC - error code 

NOTE: XR and YR are not modified (except STDIO streams return true stream number, and YR is modified for SC_RWANZ)

== DESCRIPTION
Executes a stream command. parameter: stream number in x,
stream command in a, returns error code in a.

Possible commands (as defined in link:../../include/kdefs.i65[kdefs.i65] are:

----
		SC_GET		0	same as GETSTR
		SC_REG_RD	1	increase read task counter by one
		SC_REG_WR	2	increase write task counter by one
		SC_CLR		3	empty the stream
		SC_EOF		4	closing the stream from the sender 
					side, i.e. decrease write task 
					counter by one
		SC_NUL		5	closing the stream from the receiver
					side, i.e. decrease read task 
					counter.
		SC_FRE		6	same as FRESTR
		SC_STAT		7	read stream status into ac
		SC_NUMBYTES	8	returns number of bytes in stream in AC
		SC_RWANZ	9	returns the stream write pointer in
					AC and the stream read pointer in YR

		SC_ESTAT	10	Get the error code byte in YR,
					and the normal (i.e. what you get
					with SC_STAT) stream state in AC.
		SC_SSTAT	11	Set bits in the error code byte
					each bit set in YR is set in error byte
		SC_CSTAT	12	Clear bits in the error code byte
					each bit set in YR is cleared in error 
					byte
		SC_FGPID	13	Attach a foreground process to the stream.
					Reads from other processes block/return empty
		SC_FGSIG	14	Send a signal to the currently attached foreground
					process
----

The error code byte has the following bits:

----
		SCE_PULL	%10000000  reader pulls data from sender
		SCE_PUSH	%01000000  writer pushes data to receiver
		SCE_BRK		%00100000  writer sends 'break' signal
		SCE_RERRM	%00001100  reader error condition mask
		SCE_WERRM	%00000011  writer error condition mask
----


== RETURN CODES
Error return codes are given when at return, C=1.

E_NOSTR:: no valid stream number
E_NOTIMP:: stream read counter was already zero

== SEE ALSO
link:../streams.7.adoc[streams(7)], 
link:GETSTR.2.adoc[GETSTR(2)], 
link:FRESTR.2.adoc[FRESTR(2)], 
link:GETC.2.adoc[GETC(2)], 
link:UNGETC.2.adoc[UNGETC(2)], 
link:PUTC.2.adoc[PUTC(2)]

== AUTHOR
Written by André Fachat.

== REPORTING BUGS
Please report bugs at https://github.com/fachat/GeckOS-V2/issues

