
= fopendir(1)
:doctype: manpage

== NAME
fopendir - open a directory for reading

== SYNOPSIS
Input::
	* A/Y - address of null-terminated filename, i.e. the directory path and optional filename filter
Call::
	jsr fopendir
Output::
	* C=0
		** XR - return the file number
	* C=1
		** AC - error code 

NOTE: may modify any register

== DESCRIPTION
Opens a directory for reading. The parameter given is the device, directory path, and optionally a filename filter.
Files are named as: "Device:directory/filenamefilter", where Device depends on the OS.

The filesystem might imply other limitations on filename length, if there are directories at all, or the allowed characters. Wildcards are "*" that match any string and "?" that match exacly one character. The interpretation might depend on the filesystem, i.e. may not even be the same on the same system, but on different devices. Escape sequences are "\*" and "\?". Escape sequence for "\" is "\\". 

== RETURN CODES
Error return codes are given when at return, C=1.

E_NOFILE:: 
	file not found
E_NOTDIR::
	path is not a directory


== SEE ALSO
link:../lib6502.7.adoc[lib6502(7)],
link:fopen.1.adoc[fopen(1)]
link:freaddir.1.adoc[freaddir(1)]

== AUTHOR
Written by André Fachat.

== REPORTING BUGS
Please report bugs at https://github.com/fachat/GeckOS-V2/issues

