
= stddup(1)
:doctype: manpage

== NAME
stddup - replace a standard I/O stream with another stream

== SYNOPSIS
Input::
	* X: old STDIO file nr (STDIN, STDOUT, or STDERR)
	* Y: new file descriptor
Call::
	jsr stddup
Output::
	* C=0
		** X: old file descriptor
	* C=1
		** AC - error code 

NOTE: modifies all registers

== DESCRIPTION
This call replaces a stdio file-nr (the pre-defined STDIN, STDOUT, and STDERR file-nrs) with a new file-nr. The old file-nr must not be closed, as it is when the process terminates. Instead the new file-nr returned must be closed.

== RETURN CODES
Error return codes are given when at return, C=1.

E_NOFILE:: 
	not a valid file number


== SEE ALSO
link:../lib6502.7.adoc[lib6502(7)],
link:fclose.1.adoc[fclose(1)]
link:fopen.1.adoc[fopen(1)]
link:fputc.1.adoc[fputc(1)]
link:fgetc.1.adoc[fgetc(1)]
link:fread.1.adoc[fread(1)]
link:fseek.1.adoc[fseek(1)]
link:pipe.1.adoc[pipe(1)]
link:flock.1.adoc[flock(1)]
link:fcntl.1.adoc[fcntl(1)]
link:fcmd.1.adoc[fcmd(1)]
link:dup.1.adoc[dup(1)]

== AUTHOR
Written by André Fachat.

== REPORTING BUGS
Please report bugs at https://github.com/fachat/GeckOS-V2/issues

