
= GECKOS RELEASE NOTES

== GeckOS 2.2

=== Applications
* lsh got job control

=== Devices
* new device for an NMI-driven ACIA-based RS232 (swiftlink)
* the console device has been overhauled and got a better set of control character.
	The C64 (and C128 VIC-II) now only have two consoles, but as a new feature they now include colour support.
	

=== Kernel
* *GETINFO* now returns thread info, needs iterative calls (renamed to *GETINFO2*)
* *PSEM* blocks on C=1 like any other call with option to block (renamed to *PSEM2*)
* *CHECKCHLD* also returns info for suspended children (renamed to *CHECKCHLD*)
* New *JOBCMD* call to facilitate job control functions
* Separate out timer interrupt from other interrupt sources in device's interrupt chains.

=== Ports

==== C128
* There is a new port for the Commodore 128!
	You can run it both from the VIC-II or the VDC screen of the Commodore BASIC.
	This port uses the fast serial IEC bus when available (with a 1571/1581 disk drive),
	and 2 MHz speed when started with the VDC display.

=== Build
* Cleanup of build process, using a common dist folder for generic applications / disk images
* New build targets to automatically build and run in emulator at top level
* Supports / requires xa65 v2.4.1 or later

=== More details
* link:https://github.com/fachat/GeckOS-V2/milestone/2?closed=1[Milestone 2.2 issues] on github

== GeckOS 2.1

=== Documentation
* GeckOS got its official Logo!
* rewrote all documentation in asciidoc

=== Applications
* improvements to *ps(1)*, add *setinfo(2)* to provide useful execution address
* improvements to *ls(1)*, added long options
* added *kill(1)*
* added *hexdump(1)*, *wc(1)*, *more(1)*
* Grand shell unification: *lsh(1)* graduated, *sh* is now officially deprecated and *mon* becomes *lmon(1)*

=== Devices
* Fix handshake handling of C64 userport 9600 baud interface (still work to be done in VICE)

=== Kernel
* Use of STDCIN to enable *more(1)* to read key presses from console, add *ontty(1)* to redirect that

=== Ports

==== C64
* improve keyboard mapping
* use raster interrupt as main system interrupt to free a timer

==== PET
* improve keyboard mapping on pet32k, cbm8x96 and csa
* console switcher is SHIFT-REV resp. SHIFT-TAB

==== CBM 8x96
* Optimized memory layout, so that more memory is available for user tasks (by moving system tasks completely into the second upper 32k)
* console switcher is SHIFT-REV resp. SHIFT-TAB

==== CS/A65
* Re-enabled this port since the 1.x series. 

=== Contributors
* André Fachat
* Glenn Holmer

== GeckOS 2.0.9 and before
For documentation on V2.0 and before please see link:doc/historic[the historic section].

