= DEVICES(7)
:doctype: manpage

== NAME
devices - device handling in GeckOS

== DESCRIPTION
Devices in GeckOS are basically interrupt handlers for hardware devices. Anything that is more complicated, like
opening files needs to be moderated by a userspace program. An example for this is FSDEV(8).

== USAGE
Devices are set up at boot time by registering a "device block" that may contain one or more device handlers. 
Usually, currently, there is a single device block registered from the boot rom by the kernel boot code, before 
running any userspace program. That is why even the INIT(8) program can use the console for progress output.

The interface to the devices is a single system call, DEVCMD(2), using different commands to indicate the
action to take. It is even called during the system interrupt routine.

== COMMON I/O DEVICES
This section describes various common device drivers.
Please see the port respective ports man page for availability and details.

=== VIDEO
The video device incorporates not only one but multipl devices, e.g. video1-video4
Depending on the port it uses the respective hardware of the computer for
keyboard and video.

The video has one video hardware output port only, so the video is shared
between the possible video devices. A specific key is used to switch between
the different terminals. 

As there is no way to send some kind of ioctl
message along a stream, this key has some more functions:
With Control, the key closes the stream from the sender side, thus signaling an EOF. 
With control and shift, the device is switched between the two modes.

indirect mode:: 
	keyboard events are printed on the
	screen only, not sent to the stream. If a Return occurs, the actual
	line is sent to the stream. This is default.
direct mode:: 
	all keyboard events are directly
	passed to the stream.

Supported terminal control codes are Bell, Backspace, Carriage Return,
Line Feed and Form Feed.

=== SER
Ser stands for serial device and that's what it's doing. It handles the
serial communications using ACIAs on the BIOS and on the keyboard board of the CS/A65
computer, the Swiftlink device on the C64, and even the 9600 baud userport interface on the C64. 

There are some watch outs, though. From the serial device, only RTS/CTS are handled.
A low on an incoming /RTS stops sending. If the stream to write the data
to is above the high water mark (3/4 fifo size), then /CTS is set low.
After the stream going below the low water mark (1/4 fifo size), /CTS
is set high again.

With DC_SPEED, the baud rate of the device can be set:

----
 parameter (y)      speed (baud)
 -------------------------------
 1                   50
 2                   75
 3                  109.92
 4                  134.58
 5                  150
 6                  300
 7                  600
 8                 1200
 9                 1800
 10                2400
 11                3600
 12                4800
 13                7200
 14                9600
 15               19200
----

With version 1.3.10 we now also have driver for an UART 16550A, with 16
byte builtin FIFO (oa1ds3.a65). There also is a RS232 driver for the
fast RS232 interface for the C64 by Daniel Dallmann, as
described on his homepage or in the comp.sys.cbm FAQ.

=== PAR
This device handles the (simple) centronics port where available.

== COMMON GENERIC DEVICES
This section describes the common generic devices. These are hardware-independent.

=== SPOOLER
This is a kind of serializer. You can copy one file after the other
to this device, even if the first files are not yet through. When copying
the output of the spooler to another file, e.g. the spooler
device, they appear in the same order as copied into and intact, i.e.
the files are not mixed.

=== NULDEV
This device reads a given stream until end, i.e. EOF and then closes
the stream. Like /dev/null for writing. You cannot read from it. Only
a certain number of streams can be handled before an error is returned
on open.

== SEE ALSO
DEVCMD(2)

== AUTHOR
Written by André Fachat.

== REPORTING BUGS
Please report bugs at https://github.com/fachat/GeckOS-V2/issues

