#!/bin/bash
#
# You can use VICE using this command line to start with "socat" as serial device, creating
# a Pseudo TTY for this slattach to use:
#
#	x64sc -rsuser -rsuserdev 2 -rsuserbaud 9600 -rsdev3 "|socat - PTY,link=/tmp/viceser"  -autostart osa.d64
#
# Then run this script as
#
#	sudo ./csaip -d /tmp/viceser
#
# and to debug you can use 
#
#	sudo tcpdump -i sl0 -XX -tttt -v
#
# Alternatively use
#
#	sudo ./csaip -d /tmp/viceser -l
#
# Then, in GeckOS in x64sc, run
#
#	slipd <a:ser1 >a:ser1
#
# as a minimum slip daemon that uses "a:ser1" as I/O, which is the 9600 baud userport on the C64 arch.
#

#device=/dev/cua2
device=/tmp/viceser
force=0
log=0

while [[ $# -gt 0 ]]; do
	key="$1"
	case $key in 
	-d)
		device=$2;
		shift 
		shift
		;;
	-l)
		log=1
		shift;
		;;
	*)
		break
		;;
	esac
done

device="`readlink -f $device`"

echo "Using device $device"

if [ "$1" != "stop" ]; then 

  slattach -s 9600 -p slip $device &

  echo "slattach returns $?"

  if [ $? -eq 0 ]; then

	# wait for slattch to do its work
	sleep 2

	ifconfig sl0 192.168.0.1/24 up
	#route add -host 192.168.0.64 sl0

	if [ $log -eq 1 ]; then 
		tcpdump -i sl0 -XX -tttt -v
	fi;
  else
	echo "slattach failed"
  fi;
else
  ifconfig sl0 down
fi;

